DEFAULT_SITE_CONTENT = {
    "announcement": {
        "enabled": True,
        "text": "Frete grátis para todo o Brasil em compras acima de R$ 450",
        "secondary_text": "Peças feitas à mão, uma a uma",
    },
    "hero": {
        "eyebrow": "Feito no Nordeste · desde 1987",
        "title": "Madeira com",
        "title_emphasis": "alma e história.",
        "subtitle": "Peças esculpidas à mão, onde cada veio, marca e imperfeição conta um pouco de quem somos.",
        "button_text": "Descobrir as peças",
        "button_url": "#pecas",
        "image": "/images/hero.png",
    },
    "catalog": {
        "eyebrow": "Escolhas da casa",
        "title": "Peças que guardam",
        "title_emphasis": "memória",
        "subtitle": "Do sagrado ao cotidiano, objetos que atravessam gerações e deixam a casa um pouco mais nossa.",
    },
    "featured_collection": {
        "eyebrow": "Coleção em destaque",
        "title": "Obras de Fé",
        "subtitle": "Figuras silenciosas, santos populares e símbolos talhados com a delicadeza do tempo.",
        "button_text": "Conhecer a coleção",
        "image": "/images/santo.png",
        "quote": "A mão encontra na madeira aquilo que já estava esperando para nascer.",
        "quote_author": "Mestre Severino, fundador da oficina",
    },
    "institutional": {
        "eyebrow": "Nossa história",
        "title": "O tempo também é",
        "title_emphasis": "matéria-prima.",
        "paragraph_1": "Na Casa Mamulengo, cada peça começa na escolha atenta da madeira e segue o ritmo das mãos.",
        "paragraph_2": "Trabalhamos com madeira de origem responsável e reaproveitada, mantendo vivos os saberes que passam de mestre para aprendiz.",
        "image": "/images/travessa.png",
    },
    "contact": {
        "address": "Rua dos Mestres, 87 · Olinda · Pernambuco",
        "hours": "Segunda a sexta, 9h–17h",
        "phone": "(81) 3333-1987",
        "instagram": "Instagram",
        "whatsapp": "WhatsApp",
        "whatsapp_number": "558133331987",
        "whatsapp_message": "Olá! Vim pelo site da Casa Mamulengo e gostaria de mais informações.",
        "pickup_enabled": True,
        "pickup_address": "Rua dos Mestres, 87 · Olinda · Pernambuco",
        "pickup_city": "Olinda",
        "pickup_state": "PE",
        "pickup_cep": "00000000",
        "pickup_instructions": "Após a confirmação do pagamento, combinaremos pelo WhatsApp o melhor horário para retirada.",
    },
    "seo": {
        "title": "Casa Mamulengo | Artesanato em Madeira",
        "description": "Peças de madeira feitas à mão, com tempo, memória e afeto.",
        "share_image": "/images/hero.png",
    },
}
